// <auto-generated />
using System;
using ElectionData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectionData.Data.Migrations
{
    [DbContext(typeof(ElectionDataDbContext))]
    partial class ElectionDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectionData.Data.Entities.CleanPoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Harris")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MoE")
                        .HasColumnType("numeric");

                    b.Property<string>("PollLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pollster")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<string>("SampleType")
                        .HasColumnType("text");

                    b.Property<string>("Spread")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Trump")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PollLink")
                        .IsUnique();

                    b.ToTable("Polls");
                });
#pragma warning restore 612, 618
        }
    }
}
